### ISSUE TITLE
inheriting other styles

### ISSUE THREAD

**Issue by gwijthoff** [oakstudios/mechanical-ragger#16]
Any text I place within the `<mechanical-ragger>` element won't inherit the other styles on my site. For example:

```html
<p><mechanical-ragger>
    This <a href="github.com">URL</a> won't be styled like my other links.
</mechanical-ragger></p>
```

As far as I understand it, mechanical-ragger creates an [autonomous custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements), which won't inherit anything from other HTML elements. But I'd love to be able to integrate this tool's ragging with all my existing styles. Thanks!

**Comment by danielgamage** [comment]
Thanks for the bug report! [This should be fixed now](https://codepen.io/danielgamage/pen/bGLWEod).

Try out [v0.5.0](https://github.com/oakstudios/mechanical-ragger/releases/tag/v0.5.0).

**Comment by gwijthoff** [comment]
@danielgamage thanks for the fix, and for the fantastic writing tool!
